# Copyright Louis Dionne 2013-2017
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.md or copy at http://boost.org/LICENSE_1_0.txt)
clone_folder: c:\projects\metaSMT

shallow_clone: true

os:
  - Visual Studio 2015

build:
  verbosity: detailed

configuration:
  - Debug

install:
  ############################################################################
  # All external dependencies are installed in C:\projects\deps
  ############################################################################
  - mkdir C:\projects\deps
  - cd C:\projects\deps

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - set CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-win64-x64.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\deps > nul
  - move C:\projects\deps\cmake-* C:\projects\deps\cmake # Move to a version-agnostic directory
  - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version
  #Dowload z3
  - set Z3_URL="https://github.com/Z3Prover/z3/releases/download/z3-4.5.0/z3-4.5.0-x86-win.zip"
  - appveyor DownloadFile %Z3_URL% -FileName z3-4.5.0-x86-win.zip
  - 7z x z3-4.5.0-x86-win.zip -oC:\projects\deps > nul
  - cp "C:\projects\metaSMT\Z3Config.cmake" "C:\projects\deps\z3-4.5.0-x86-win"
  #Download boost
  - set BOOST_URL="https://sourceforge.net/projects/boost/files/boost-binaries/1.60.0/boost_1_60_0-msvc-14.0-32.exe/download"
  - appveyor DownloadFile %BOOST_URL% -FileName boost.exe
  - boost.exe /DIR="C:\projects\deps\boost" /silent

before_build:
  - call "%VS140COMNTOOLS%VsDevCmd.bat"
  - cd C:\projects\metaSMT
  #- git status
  #- git submodule update --init --recursive


build_script:
  - cd
  - mkdir build
  - cp build.bat build\build.bat
  - cd build
  - set PATH=C:\projects\deps\boost\lib32-msvc-14.0;%PATH%
  - build.bat
  - appveyor PushArtifact CMakeFiles/CMakeError.log
  - echo %PATH%
